FROM php:8.2-apache

CMD ["apache2-foreground"]

# RUN <<EOF
# apt update
# apt install -y --no-install-recommends git
# EOF


# Why this?
# RUN <<EOF
# useradd -s /bin/bash -m vscode
# groupadd docker
# usermod -aG docker vscode
# EOF

CMD ["apache2-foreground"]